apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "myapp.fullname" . }}
  annotations:
    {{- if .Values.irsa.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn | quote }}
    {{- end }}